---
- hosts: desktops
  pre_tasks:
    - name: update cache
      become: true
      tags: always
      apt:
        update_cache: yes

  tasks:
    - import_tasks: "tasks/basics.yml"
    - import_tasks: "tasks/dotfiles.yml"
    - import_tasks: "tasks/gui.yml"
    - import_tasks: "tasks/gui-wayland.yml"
