- name: Install cli apps
  become: true
  apt:
    name:
      - tmux
      - fish
      - lsd
      - bat
      - ripgrep
      - fzf
      - zsh
    state: present
  tags: &tags_for_cli ["cli"]

- name: Link ~/.config/tmux
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/c/dotfiles/config/tmux"
    dest: "{{ ansible_env.HOME }}/.config/tmux"
    state: link
  tags: *tags_for_cli

- name: Link ~/.config/fish
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/c/dotfiles/config/fish"
    dest: "{{ ansible_env.HOME }}/.config/fish"
    state: link
  tags: *tags_for_cli

- name: Link ~/.zshrc
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/c/dotfiles/zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
  tags: *tags_for_cli

- name: Link ~/.config/antigen
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/c/dotfiles/config/antigen"
    dest: "{{ ansible_env.HOME }}/.config/antigen"
    state: link
  tags: *tags_for_cli

- name: Link ~/bin
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/c/dotfiles/bin"
    dest: "{{ ansible_env.HOME }}/bin"
    state: link
  tags: *tags_for_cli

- name: Change shell to zsh
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    shell: "/usr/bin/zsh"
  tags: *tags_for_cli
