- name: Install wayland apps
  become: true
  apt:
    name:
      - xdg-desktop-portal-wlr
      - wl-clipboard
      - wdisplays
      - waypipe
      - foot
      - wtype
    state: present

- name: Link ~./config/foot
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/c/dotfiles/config/foot"
    dest: "{{ ansible_env.HOME }}/.config/foot"
    state: link
