- name: Check if rustup is installed
  stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin/rustup"
  changed_when: false
  register: rustup_bin

- when: not rustup_bin.stat.exists
  block:
    - name: Download rustup installer
      get_url:
        url: "https://sh.rustup.rs"
        dest: /tmp/rustup.sh
        mode: 0755

    - name: Install rust...
      ansible.builtin.command:
        cmd: sh /tmp/rustup.sh -y
        creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"

  always:
    - name: Cleanup rustup installer
      file:
        path: /tmp/rustup.sh
        state: absent

- name: Install starship
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.cargo/bin/cargo install starship"
    creates: "{{ ansible_env.HOME }}/.cargo/bin/starship"

- name: Install fnm
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.cargo/bin/cargo install fnm"
    creates: "{{ ansible_env.HOME }}/.cargo/bin/fnm"
